// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/catalogs/catalog": {
            "get": {
                "description": "Endpoint use by agent to retrieve the catalog that they need to execute",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalogs"
                ],
                "summary": "Retrieve catalog to execute",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.GetCatalog"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/certificates/retrieve": {
            "post": {
                "description": "retrieve a node signed certificate",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "certificates"
                ],
                "summary": "Retrieve a certificate once it has been signed",
                "parameters": [
                    {
                        "description": "Name of the node, along the CSR",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.RetrieveSignedCertificate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.RetrieveSignedCertificate"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/certificates/root": {
            "get": {
                "description": "get root ca from server",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "certificates"
                ],
                "summary": "Used to get the root CA from the server",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.GetRootCA"
                        }
                    }
                }
            }
        },
        "/v1/certificates/submit": {
            "post": {
                "description": "submit an unsigned certificate",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "certificates"
                ],
                "summary": "Used to submit a certificate",
                "parameters": [
                    {
                        "description": "Name of the node, along the CSR",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.SubmitCertificateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/responses.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.IncludedResources": {
            "type": "object",
            "properties": {
                "loaded_resources": {
                    "type": "array",
                    "items": {}
                },
                "resources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Resource"
                    }
                }
            }
        },
        "models.Resource": {
            "type": "object",
            "properties": {
                "data": {},
                "present": {
                    "type": "boolean"
                },
                "require": {
                    "$ref": "#/definitions/models.ResourceRequire"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "when": {
                    "type": "string"
                }
            }
        },
        "models.ResourceRequire": {
            "type": "object",
            "properties": {
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "models.Role": {
            "type": "object",
            "properties": {
                "included_resources": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/models.IncludedResources"
                    }
                },
                "loaded_resources": {
                    "type": "array",
                    "items": {}
                },
                "name": {
                    "type": "string"
                },
                "resources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Resource"
                    }
                },
                "templates": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "variables": {
                    "type": "object",
                    "additionalProperties": {}
                }
            }
        },
        "requests.RetrieveSignedCertificate": {
            "type": "object",
            "required": [
                "csr",
                "node_name"
            ],
            "properties": {
                "csr": {
                    "type": "string"
                },
                "node_name": {
                    "type": "string"
                }
            }
        },
        "requests.SubmitCertificateRequest": {
            "type": "object",
            "required": [
                "csr",
                "node_name"
            ],
            "properties": {
                "csr": {
                    "type": "string"
                },
                "node_name": {
                    "type": "string"
                }
            }
        },
        "responses.ErrorResponse": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "responses.GetCatalog": {
            "type": "object",
            "properties": {
                "resources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Resource"
                    }
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Role"
                    }
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "variables": {
                    "type": "object",
                    "additionalProperties": {}
                }
            }
        },
        "responses.GetRootCA": {
            "type": "object",
            "properties": {
                "certificate": {
                    "type": "string"
                }
            }
        },
        "responses.MessageResponse": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "string"
                }
            }
        },
        "responses.RetrieveSignedCertificate": {
            "type": "object",
            "properties": {
                "certificate": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
