name: run-tests
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    container: golang:1.27.0-trixie
    steps:
      - uses: actions/checkout@v6
      - name: Run golang tests
        run: go test -coverprofile=coverage.out ./...
  lint:
    runs-on: ubuntu-latest
    container: golang:1.27.0-trixie
    steps:
      - uses: actions/checkout@v6
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12

